[build]
  publish = "frontend/dist/frontend"
  command = "./netlify-build.sh"

[functions]
  directory = "backend/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
