[build]
  command = "cd frontend && npm install && npx ng build"
  publish = "dist/frontend"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200