[build]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Angular routing fix (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200