[build]
  command = "cd frontend && npm install && npx ng build --prod"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"  # If you have serverless functions inside the backend

[context.production.environment]
  NODE_ENV = "production"