[build]
  command = "cd frontend && npm install && npm run build:prod"
  publish = "dist/frontend"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
