[build]
  publish = "dist/frontend/browser"
  command = "bash netlify-build.sh"

[functions]
  directory = "dist/backend"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Angular routing fix (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
